version: "3.9"

services:
  backend:
    image: tourism-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: tourism-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tourism
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
