name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  mains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  tests:
    runs-on: ubuntu-latest
    needs: mains
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
  build:
    runs-on: self-hosted
    needs: [tests, mains]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: SSH to server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
          docker-compose -f /path/to/docker-compose.yaml down

          docker-compose -f /path/to/docker-compose.yaml up -d
          EOF
